{"name": "test_4", "status": "failed", "statusDetails": {"message": "AssertionError: assert \"新增商户注册失败nest...id_mail_role'\" == '新增成功'\n  + 新增成功\n  - 新增商户注册失败nested exception is org.apache.ibatis.exceptions.PersistenceException: \n  - ### Error updating database.  Cause: Duplicate entry '265-161.165465.5646wsfih@.qq.com-MERCHANT' for key 'index_app_id_mail_role'\n  - ### The error may involve defaultParameterMap\n  - ### The error occurred while setting parameters\n  - ### SQL: INSERT INTO user (         id,gmt_create,gmt_modify,version,is_deleted,features,         app_id,login_name,mobile,mail,pass_wd,trade_pass_wd,user_name,sex,status,role,parent_user_id,foreign_id         ) VALUES (         ?,now(),now(),0,0,?,         ?,?,?,?,?,?,?,         ?,?...\n  \n  ...Full output truncated (2 lines hidden), use '-vv' to show", "trace": "self = <case.info.test_user.Test_drgapi_user object at 0x04E6BAB0>, login_fix = <requests.sessions.Session object at 0x04D95FB0>, delect_spman_center_merchant = None, delect_inside_user_center_user = None\n\n    def test_4(self,login_fix,delect_spman_center_merchant,delect_inside_user_center_user):\n        '''新增发包方'''\n        s = login_fix\n        DF = DRG_func(s)\n        DF.login()\n        result = DF.add_merchant()\n        print(result)\n>       assert result[\"message\"][\"content\"] == \"新增成功\"\nE       assert \"新增商户注册失败nest...id_mail_role'\" == '新增成功'\nE         + 新增成功\nE         - 新增商户注册失败nested exception is org.apache.ibatis.exceptions.PersistenceException: \nE         - ### Error updating database.  Cause: Duplicate entry '265-161.165465.5646wsfih@.qq.com-MERCHANT' for key 'index_app_id_mail_role'\nE         - ### The error may involve defaultParameterMap\nE         - ### The error occurred while setting parameters\nE         - ### SQL: INSERT INTO user (         id,gmt_create,gmt_modify,version,is_deleted,features,         app_id,login_name,mobile,mail,pass_wd,trade_pass_wd,user_name,sex,status,role,parent_user_id,foreign_id         ) VALUES (         ?,now(),now(),0,0,?,         ?,?,?,?,?,?,?,         ?,?...\nE         \nE         ...Full output truncated (2 lines hidden), use '-vv' to show\n\ntest_user.py:62: AssertionError"}, "description": "新增发包方", "steps": [{"name": "登录获取cookie", "status": "passed", "start": 1585016615076, "stop": 1585016615271}, {"name": "新增发包方", "status": "passed", "start": 1585016615271, "stop": 1585016615400}], "attachments": [{"name": "stdout", "source": "a84b0815-a69b-4bf7-aacb-3657e631399d-attachment.txt", "type": "text/plain"}], "start": 1585016615076, "stop": 1585016615402, "uuid": "b6381922-2333-4eab-a762-7071f7d154a6", "historyId": "cca4dcdf77e2ec1d48cac0f4f71bc8f7", "testCaseId": "59acb1158f21241d088d32caffc8b59c", "fullName": "case.info.test_user.Test_drgapi_user#test_4", "labels": [{"name": "feature", "value": "达人馆用户管理模块"}, {"name": "parentSuite", "value": "case.info"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "Test_drgapi_user"}, {"name": "host", "value": "DESKTOP-OKUD34E"}, {"name": "thread", "value": "1892-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.info.test_user"}]}